name: pr-ebpf
on:
  pull_request:
    paths:
      - "tracee-ebpf/**"
jobs:
  build-test:
    env:
      DOCKER_BUILDKIT: '1'
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: tracee-ebpf
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
            echo "Congrats! There is nothing to fix."
          else
            echo "The following lines should be fixed."
            gofmt -s -d .
            exit 1
          fi
      # - name: setting buildxs
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx
      #   with:
      #     install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build tracee-builder
        #run: make all DOCKER=1
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./tracee-ebpf/Dockerfile.builder
          #load: true
          tags: tracee-builder:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=docker
          platforms: linux/amd64

      - name: Test
        run: DOCKER_BUILDKIT=1 make test DOCKER=1
